version: '3'

services:
  db:
    image: postgres:15.4
    expose:
      - 5437:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  data: {}
