name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [v*]
  pull_request:
    branches: [ "main" ]
    types: [auto_merge_enabled ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    #checkout code
    - name: Checkout
      uses: actions/checkout@v4
    
    #for multiple platforms
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3    
    # login to own dockerhub 
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        # GitHub Repo->Settings->Secrets then add username and password
        # it should be the same with name here 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    #build docker image and push it to the docker hub
    - uses: docker/build-push-action@v5
      name: Build the Docker image and push
      with:
            # whether need to push
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/pg:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/pg:${{ github.event.issue.number }}
            