name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [auto_merge_enabled ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    #checkout code
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v5
      name: Build the Docker image and push
      with:
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/pg:${{date 'YYYYMMDD'}}